DROP TABLE IF EXISTS MESSAGES;
  
CREATE TABLE MESSAGES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  sender VARCHAR(50) NOT NULL,
  recipient VARCHAR(50) NOT NULL,
  content VARCHAR(250) DEFAULT NULL
);

